### ISSUE TITLE
attempting to encode bytes of wrong size produces a misleading error message

### ISSUE THREAD

**Issue by ldct** [ApeWorX/eth-abi#101]
* Version: 2.0.0b1
* Python: 3.7
* OS: macos

### What was wrong?

```
>>> eth_abi.encode_single("address", b"a"*20)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00aaaaaaaaaaaaaaaaaaaa'
```

```
>>> eth_abi.encode_single("address", b"a"*21)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xuanji/gits/cf/plasma-cash/venv/lib/python3.7/site-packages/eth_abi/abi.py", line 43, in encode_single
    return encoder(arg)
  File "/Users/xuanji/gits/cf/plasma-cash/venv/lib/python3.7/site-packages/eth_abi/encoding.py", line 73, in __call__
    return self.encode(value)
  File "/Users/xuanji/gits/cf/plasma-cash/venv/lib/python3.7/site-packages/eth_abi/encoding.py", line 178, in encode
    self.validate_value(value)
  File "/Users/xuanji/gits/cf/plasma-cash/venv/lib/python3.7/site-packages/eth_abi/encoding.py", line 456, in validate_value
    cls.__name__,
eth_abi.exceptions.EncodingTypeError: Value of type <class 'bytes'> cannot be encoded by AddressEncoder
```

contrary to what the error message says, `bytes` can be encoded by AddressEncoder

### How can it be fixed?

**Comment by stefanmendoza** [comment]
The reason this is thrown is because `is_address` calls `is_binary_address`:

https://github.com/ethereum/eth-utils/blob/v2.0.0-alpha.0/eth_utils/address.py#L23-L32

Since that method checks whether the passed in address is `bytes` _and_ valid length, there would be no way to discern from the response of `is_address` what actually caused it to be `False`, just that it didn't pass the validation. And since `str` type works for hexstrings:
```
>>> from eth_account.account import Account
>>> import eth_abi
>>> acct = Account.create()
>>> acct.address; type(acct.address)
'0x73445e747C4103638F84d9D91e7b01239599D7e5'
<class 'str'>
>>> eth_abi.encode_single('address', acct.address)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00sD^t|A\x03c\x8f\x84\xd9\xd9\x1e{\x01#\x95\x99\xd7\xe5'
```

I don't think we can just add an `is_bytes` check here.

**Comment by pipermerriam** [comment]
I'm thinking something like this:

```python
if not is_address(value):
    if is_string(value):
        raise EncodingTypeError("Unable to parse {0} as an address.  Supported formats are ...")
    else:
        raise EncodingTypeError("Cannot encode value of type {0} as an address")
```
